name: Build and push Docker image to Docker Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: bookhub
  VERSION_NUMBER: 1.${{ github.run_number }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic-release.outputs.version }}
    steps:
      - id: semantic-release
        run: |
          npx semantic-release
          VERSION=$(cat VERSION)
          echo "Resolved version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  push_to_registry:
    needs: release
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Action For Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.0
        with:
          semantic_version: 19.0.5
          branches: |
            [
              'master',  'MirolimMajidov-TestVersioning',
              {
                name: 'deploy-dev',
                prerelease: true
              },
              {
                name: 'deploy-stating',
                prerelease: true
              }
            ]
          tag_format: "v${version}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        id: docker_build_identity
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ././Dockerfile
          push: ${{ github.ref == 'refs/heads/master' }}  # Ensures pushing only on master
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_NUMBER }}
