# .github/workflows/main.yml
name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "master", "MirolimMajidov-TestVersioning" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: bookhub
  PROJECT_PATH: BookHub.csproj
  DOCKER_FILE_PATH: ./Dockerfile

jobs:
  versioning:
    uses: ./.github/workflows/versioning.yml
    with:
      PROJECT_PATH: ${{ env.PROJECT_PATH }}

  docker_build_and_push:
    needs: versioning
    uses: ./.github/workflows/docker-build-push.yml
    with:
      DOCKER_FILE_PATH: ${{ env.DOCKER_FILE_PATH }}
      REGISTRY: ${{ env.REGISTRY }}
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      NEW_VERSION: ${{ needs.versioning.outputs.NEW_VERSION }}
