name: Docker Build and Push

on:
  workflow_call:
    inputs:
      DOCKER_FILE_PATH:
        required: true
        type: string
      REGISTRY:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      NEW_VERSION:
        required: true
        type: string

    secrets:
      DOCKERHUB_TOKEN:
        description: 'Docker Hub token'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        id: login_docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.REGISTRY }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: publish_docker_image
        uses: docker/build-push-action@v6
        with:
          file: ${{ inputs.DOCKER_FILE_PATH }}
          push: true
          tags: |
            ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}:latest
            ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}:${{ inputs.NEW_VERSION }}
