name: Docker Operations

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image_name:
        required: true
        type: string
      push:
        required: true
        type: boolean
      version_number:
        required: true
        type: string
      new_version:
        required: true
        type: string

jobs:
  docker_operations:
    name: Log in to Docker Hub and build & push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        id: login_docker_hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        id: publish_docker_image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ inputs.push }}
          tags: |
            ${{ inputs.registry }}/${{ inputs.image_name }}:latest
            ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.new_version }}