name: Docker Build and Push

on:
  workflow_call:
    inputs:
      docker_file_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      version:
        required: true
        type: string

    secrets:
      username:
        description: 'Docker Hub username'
        required: true
      password:
        description: 'Docker Hub token'
        required: true

jobs:
  Staging:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        id: login_docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build and push Docker image
        id: publish_docker_image
        uses: docker/build-push-action@v6
        with:
          file: ${{ inputs.docker_file_path }}
          push: true
          tags: |
            ${{ secrets.username }}/${{ inputs.image_name }}:latest
            ${{ secrets.username }}/${{ inputs.image_name }}:${{ inputs.version }}
