name: Build and push Docker image to Docker Hub

on:
  push:
    branches: [ "master", "MirolimMajidov-TestVersioning" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: bookhub
  PROJECT_PATH: BookHub.csproj
  DOCKER_FILE_PATH: ./Dockerfile

permissions:
  contents: write  # Grant the workflow permission to push to the repository

jobs:
  CheckOutCode:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
  
  versioning:
    needs: CheckOutCode
    uses: ./.github/workflows/versioning.yml
    with:
      PROJECT_PATH: ${{ env.PROJECT_PATH }}

  docker_build_and_push:
    needs: versioning
    uses: ./.github/workflows/docker-build-push.yml
    with:
      DOCKER_FILE_PATH: ${{ env.DOCKER_FILE_PATH }}
      REGISTRY: ${{ env.REGISTRY }}
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      NEW_VERSION: ${{ needs.versioning.outputs.NEW_VERSION }}