name: Build and push Docker image to Docker Hub

on:
  push:
    branches: [ "master", "MirolimMajidov-TestVersioning" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: bookhub
  PUSH: true
  VERSION_NUMBER: 1.${{ github.run_number }}

permissions:
  contents: write  # Grant the workflow permission to push to the repository

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Extract and update version from .csproj
        id: update_version
        run: |
          # Extract current version from the .csproj file
          VERSION=$(cat BookHub.csproj | grep '<Version>' | sed -e 's/<[^>]*>//g' | xargs || echo "1.0.0")
          
          # Split the version into major, minor, and patch components
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
          # Increment the patch version
          PATCH=$((PATCH+1))
          
          # Create the new version
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          
          # Replace the version in the .csproj file
          sed -i "s/<Version>.*<\/Version>/<Version>$NEW_VERSION<\/Version>/" BookHub.csproj
          
          # Save the new version as an environment variable
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

          # Set up git
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Commit and push the updated .csproj file back to the same branch
          git checkout -B MirolimMajidov-TestVersioning  # Ensure you're on the correct branch
          git add BookHub.csproj
          git commit -m "Update version to $NEW_VERSION"
          git push origin MirolimMajidov-TestVersioning

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ env.PUSH }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_NUMBER }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.NEW_VERSION }}
