name: Build and push Docker image to Docker Hub

on:
  push:
    branches: [ "master", "MirolimMajidov-TestVersioning" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write  # Grant the workflow permission to push to the repository

jobs:
  CheckOutCode:
    name: Check out repository code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

  Versioning:
    needs: CheckOutCode
    uses: ./.github/workflows/versioning.yml
    with:
      project_path: 'BookHub.csproj'

  Release:
    needs: versioning
    uses: ./.github/workflows/docker-build-push.yml
    with:
      docker_file_path: './Dockerfile'
      image_name: 'bookhub'
      version: ${{ needs.versioning.outputs.NEW_VERSION }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
